# Generated by Django 3.1.3 on 2020-11-26 16:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Customers_Sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telepone',
            name='passphone_number',
        ),
        migrations.AddField(
            model_name='telepone',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='EG'),
        ),
    ]
