# Generated by Django 3.1 on 2021-07-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers_Sales', '0009_auto_20201127_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='customeremail',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='customerimage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='telephone',
            name='owner',
        ),
    ]
