# Generated by Django 3.1 on 2021-08-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers_Sales', '0010_auto_20210711_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telephone',
        ),
    ]
