# Generated by Django 3.2.6 on 2022-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers_Sales', '0012_auto_20211004_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Ahmed', max_length=150),
            preserve_default=False,
        ),
    ]
