# Generated by Django 3.2.6 on 2022-04-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers_Sales', '0013_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='inactive',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prospect',
        ),
        migrations.DeleteModel(
            name='CustomerType',
        ),
        migrations.AddField(
            model_name='customerphone',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers_Sales.customer'),
        ),
    ]
