# Generated by Django 3.1.5 on 2021-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
