# Generated by Django 3.2.6 on 2022-03-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20220324_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieremail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplierphone',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
