# Generated by Django 3.0.7 on 2021-01-09 19:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sole_proprietorship', '0010_auto_20210103_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('general_ledeger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sole_proprietorship.Accounts')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(help_text='Specify name for this setting', max_length=100)),
                ('terms', models.IntegerField(choices=[(1, 'Cash On Demand'), (2, 'Due in number of days'), (3, 'Due at the end of month'), (4, 'Due on the next Month'), (5, 'let me specify the due date DD-MM-YYY')])),
                ('days', models.PositiveSmallIntegerField(blank=True, help_text='discount in days', null=True, validators=[django.core.validators.MaxValueValidator(32)])),
                ('discount_percentage', models.FloatField(help_text='Enter discount like this 5%>>will be  5 not 0.05')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.PositiveIntegerField()),
                ('number_of_unit', models.PositiveIntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
        ),
    ]
