# Generated by Django 3.1 on 2021-06-25 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sole_proprietorship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsalesterm',
            name='accounts_payable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sales_term_accounts_payable_account', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sales_term_cash_account', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='freight_in_account',
            field=models.ForeignKey(blank=True, help_text='choose A/p or Cash to determine if you paid this cost cash or not', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_in_account', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payinvoice',
            name='purchase_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinventory'),
        ),
        migrations.AddField(
            model_name='inventoryreturn',
            name='inventory_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryprice'),
        ),
        migrations.AddField(
            model_name='inventoryprice',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryprice',
            name='purchase_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinventory'),
        ),
        migrations.AddField(
            model_name='inventoryimag',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='general_ledeger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
