# Generated by Django 3.2.6 on 2022-03-19 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('sole_proprietorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsalesterm',
            name='COGS',
            field=models.ForeignKey(help_text='Select Cost of goods sold Account', on_delete=django.db.models.deletion.CASCADE, related_name='COGS', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='accounts_payable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sales_term_accounts_payable_account', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='accounts_receivable',
            field=models.ForeignKey(help_text='Select Accounts receivable account', on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sales_term_cash_account', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='freight_in_account',
            field=models.ForeignKey(help_text='choose A/p or Cash to determine if you paid this cost cash or not', on_delete=django.db.models.deletion.CASCADE, related_name='freight_in_account', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='freight_out_account',
            field=models.ForeignKey(help_text='choose frieght out expense account', on_delete=django.db.models.deletion.CASCADE, related_name='freight_out_account', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='sales_allowance',
            field=models.ForeignKey(help_text='Select Sales allowance account', on_delete=django.db.models.deletion.CASCADE, related_name='sales_allowance', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='sales_discount',
            field=models.ForeignKey(help_text='Select Sales discount account', on_delete=django.db.models.deletion.CASCADE, related_name='sales_discount', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='sales_return',
            field=models.ForeignKey(help_text='Select Sales return account', on_delete=django.db.models.deletion.CASCADE, related_name='sales_return', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='sales_revenue',
            field=models.ForeignKey(help_text='Select Sales revenue account', on_delete=django.db.models.deletion.CASCADE, related_name='sales_revenue', to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='payinvoice',
            name='purchase_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinventory'),
        ),
        migrations.AddField(
            model_name='inventoryreturn',
            name='inventory_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryprice'),
        ),
        migrations.AddField(
            model_name='inventoryprice',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryprice',
            name='purchase_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinventory'),
        ),
        migrations.AddField(
            model_name='inventoryimag',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryallowance',
            name='inventory_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryprice'),
        ),
        migrations.AddField(
            model_name='inventoryallowance',
            name='purchase_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='general_ledeger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sole_proprietorship.accounts'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='purchaseinventory',
            index=models.Index(fields=['status'], name='pur_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinventory',
            index=models.Index(fields=['purchase_date'], name='purchase_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['item_name'], name='item_name_idx'),
        ),
    ]
