# Generated by Django 3.0.7 on 2021-01-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210111_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryprice',
            name='purchase_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.PurchaseInventory'),
            preserve_default=False,
        ),
    ]
