# Generated by Django 3.2.6 on 2022-03-21 18:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
