# Generated by Django 3.1 on 2021-06-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210625_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinventory',
            name='num',
        ),
    ]
