# Generated by Django 3.0.7 on 2021-01-11 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryprice_purchase_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsalesterm',
            name='days',
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='discount_in_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='num_of_days_due',
            field=models.PositiveSmallIntegerField(default=1, help_text='in case of you want to specifynumber of days due'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='due_date',
            field=models.DateField(blank=True, help_text='optional if you want to specify it by yourself', null=True),
        ),
    ]
