# Generated by Django 3.1 on 2021-06-26 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_purchaseinventory_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='payinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
