# Generated by Django 3.1 on 2021-06-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_payinvoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('inventory_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryprice')),
                ('purchase_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinventory')),
            ],
        ),
    ]
