# Generated by Django 3.0.7 on 2021-01-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210111_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinventory',
            old_name='date',
            new_name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='paymentsalesterm',
            name='due_date',
        ),
        migrations.AddField(
            model_name='purchaseinventory',
            name='due_date',
            field=models.DateField(blank=True, help_text='optional if you want to specify it by yourself', null=True),
        ),
    ]
