# Generated by Django 3.0.7 on 2021-01-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210111_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='terms',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'Cash On Demand'), (2, 'Due in number of days'), (3, 'Due at the end of month'), (4, 'Due on the next Month'), (5, 'let me specify the due date DD-MM-YYY')]),
        ),
    ]
