# Generated by Django 3.1 on 2021-07-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinventory',
            name='allowance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinventory',
            name='cost_returned',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinventory',
            name='num_returend',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinventory',
            name='total_amount_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
