# Generated by Django 3.1 on 2021-07-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0004_transaction_purchase_allowance'),
        ('inventory', '0006_auto_20210703_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsalesterm',
            name='COGS',
            field=models.ForeignKey(default=1, help_text='Select Cost of goods sold Account', on_delete=django.db.models.deletion.CASCADE, related_name='COGS', to='sole_proprietorship.accounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='freight_out_account',
            field=models.ForeignKey(default=1, help_text='choose frieght out expense account', on_delete=django.db.models.deletion.CASCADE, related_name='freight_out_account', to='sole_proprietorship.accounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='pay_freight_out',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Accounts Payable')], default=1, help_text='How You will pay frieht-out?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='freight_in_account',
            field=models.ForeignKey(default=1, help_text='choose A/p or Cash to determine if you paid this cost cash or not', on_delete=django.db.models.deletion.CASCADE, related_name='freight_in_account', to='sole_proprietorship.accounts'),
            preserve_default=False,
        ),
    ]
