# Generated by Django 3.0.7 on 2021-01-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210112_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinventory',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.PaymentSalesTerm'),
            preserve_default=False,
        ),
    ]
