# Generated by Django 3.1 on 2021-07-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0004_transaction_purchase_allowance'),
        ('inventory', '0008_sale_sold_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsalesterm',
            name='sales_revenue',
            field=models.ForeignKey(default=1, help_text='Select Sales revenue account', on_delete=django.db.models.deletion.CASCADE, related_name='sales_revenue', to='sole_proprietorship.accounts'),
            preserve_default=False,
        ),
    ]
