# Generated by Django 3.1 on 2021-07-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0004_transaction_purchase_allowance'),
        ('inventory', '0009_paymentsalesterm_sales_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsalesterm',
            name='accounts_receivable',
            field=models.ForeignKey(default=1, help_text='Select Accounts receivable account', on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='sole_proprietorship.accounts'),
            preserve_default=False,
        ),
    ]
