# Generated by Django 3.0.7 on 2021-01-14 13:53

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchaseinventory_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryImag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, help_text='Inventory image', null=True, upload_to=inventory.models.inventory_imag_directory_path)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
        ),
    ]
