# Generated by Django 3.0.7 on 2021-01-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryimag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryimag',
            options={'verbose_name': 'Inventory Image', 'verbose_name_plural': 'Inventory Images'},
        ),
        migrations.AlterField(
            model_name='inventoryimag',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='inventory.Inventory'),
        ),
    ]
