# Generated by Django 3.1 on 2021-07-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_paymentsalesterm_accounts_receivable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sub_total',
        ),
    ]
