# Generated by Django 3.1 on 2021-07-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0005_auto_20210711_1153'),
        ('inventory', '0011_remove_sale_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsalesterm',
            name='sales_allowance',
            field=models.ForeignKey(default=1, help_text='Select Sales allowance account', on_delete=django.db.models.deletion.CASCADE, related_name='sales_allowance', to='sole_proprietorship.accounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='sales_return',
            field=models.ForeignKey(default=1, help_text='Select Sales return account', on_delete=django.db.models.deletion.CASCADE, related_name='sales_return', to='sole_proprietorship.accounts'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_returned', models.PositiveIntegerField()),
                ('sold_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sold_item')),
            ],
        ),
    ]
