# Generated by Django 3.0.7 on 2021-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_purchaseinventory_frieght_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryprice',
            name='cost_per_unit',
            field=models.FloatField(),
        ),
    ]
