# Generated by Django 3.1 on 2021-07-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_salesreturn_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('sales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.sale')),
            ],
        ),
    ]
