# Generated by Django 3.0.7 on 2021-01-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0010_auto_20210103_1318'),
        ('inventory', '0013_auto_20210116_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsalesterm',
            name='general_ledeger_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sole_proprietorship.Accounts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='terms',
            field=models.IntegerField(choices=[(0, 'Pay CASH'), (1, 'Cash On Demand'), (2, 'Due in number of days'), (3, 'Due at the end of month'), (4, 'Due on the next Month'), (5, 'let me specify the due date DD-MM-YYY')], default=0),
        ),
    ]
