# Generated by Django 3.1 on 2021-07-15 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_salesallowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='discount_in_days',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='discount_percentage',
            field=models.FloatField(default=0, help_text='Enter discount like this 5%>>will be  5 not 0.05'),
        ),
        migrations.AlterField(
            model_name='salesallowance',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sale'),
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sale')),
            ],
        ),
    ]
