# Generated by Django 3.0.7 on 2021-01-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210116_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsalesterm',
            name='general_ledeger_account',
        ),
    ]
