# Generated by Django 3.0.7 on 2021-01-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0010_auto_20210103_1318'),
        ('inventory', '0015_remove_paymentsalesterm_general_ledeger_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsalesterm',
            name='general_ledeger_account',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='sole_proprietorship.Accounts'),
            preserve_default=False,
        ),
    ]
