# Generated by Django 3.0.7 on 2021-01-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_paymentsalesterm_general_ledeger_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_returned', models.PositiveIntegerField()),
                ('inventory_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
        ),
    ]
