# Generated by Django 3.1 on 2021-07-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_paymentsalesterm_sales_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='num_of_days_due',
            field=models.PositiveSmallIntegerField(default=0, help_text='in case of you want to specify number of days due'),
        ),
    ]
