# Generated by Django 3.0.7 on 2021-01-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventoryreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreturn',
            name='inventory_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryPrice'),
        ),
    ]
