# Generated by Django 3.1 on 2021-07-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20210717_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinventory',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
