# Generated by Django 3.0.7 on 2021-01-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20210116_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='num_of_days_due',
            field=models.PositiveSmallIntegerField(help_text='in case of you want to specify number of days due'),
        ),
    ]
