# Generated by Django 3.1 on 2021-08-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20210722_2359'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['item_name'], name='item_name_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinventory',
            index=models.Index(fields=['status'], name='pur_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinventory',
            index=models.Index(fields=['purchase_date'], name='purchase_date_idx'),
        ),
    ]
