# Generated by Django 3.0.7 on 2021-01-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20210119_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('purchase_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.PurchaseInventory')),
            ],
        ),
    ]
