# Generated by Django 3.2.6 on 2021-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20211004_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Category'),
        ),
    ]
