# Generated by Django 3.0.7 on 2021-01-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_purchaseinventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinventory',
            name='cost_returned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinventory',
            name='net_purchases',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinventory',
            name='num_returend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinventory',
            name='total_amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinventory',
            name='total_purchases',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
