# Generated by Django 3.2.6 on 2022-02-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_inventory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
