# Generated by Django 3.1.5 on 2021-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20210125_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalForInventoryReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
