# Generated by Django 3.1.5 on 2021-01-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_journalforinventoryreturn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalForInventoryReturn',
        ),
    ]
