# Generated by Django 3.2.6 on 2022-02-26 20:54

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20220225_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryimag',
            name='img',
            field=models.ImageField(help_text='Inventory image', upload_to=inventory.models.inventory_imag_directory_path),
        ),
    ]
