# Generated by Django 3.1 on 2021-02-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0011_auto_20210131_1334'),
        ('inventory', '0024_delete_journalforinventoryreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsalesterm',
            name='freight_in_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_in_account', to='sole_proprietorship.accounts'),
        ),
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='general_ledeger_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sole_proprietorship.accounts'),
        ),
    ]
