# Generated by Django 3.1 on 2021-02-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0012_auto_20210223_1614'),
        ('inventory', '0025_auto_20210223_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='freight_in_account',
            field=models.ForeignKey(blank=True, help_text='choose A/p or Cash to determine if you paid this cost cash or not', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_in_account', to='sole_proprietorship.accounts'),
        ),
        migrations.AlterField(
            model_name='paymentsalesterm',
            name='general_ledeger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sole_proprietorship.accounts'),
        ),
    ]
