# Generated by Django 3.1 on 2021-02-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0012_auto_20210223_1614'),
        ('inventory', '0026_auto_20210226_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsalesterm',
            name='general_ledeger_account',
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='accounts_payable',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, related_name='payment_sales_term_accounts_payable_account', to='sole_proprietorship.accounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsalesterm',
            name='cash_account',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='payment_sales_term_cash_account', to='sole_proprietorship.accounts'),
            preserve_default=False,
        ),
    ]
