# Generated by Django 3.1 on 2020-08-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='comment',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
