# Generated by Django 3.1 on 2021-06-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0002_transaction_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
