# Generated by Django 3.1 on 2020-08-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0002_auto_20200816_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='comment',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
