# Generated by Django 3.1 on 2021-07-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryallowance'),
        ('sole_proprietorship', '0003_remove_transaction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase_allowance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryallowance'),
        ),
    ]
