# Generated by Django 3.0.7 on 2021-01-01 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sole_proprietorship', '0004_auto_20210101_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingperiodconfig',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fs_reporting_period', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
