# Generated by Django 3.1 on 2021-07-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_paymentsalesterm_accounts_receivable'),
        ('sole_proprietorship', '0004_transaction_purchase_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sold_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.sold_item'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Purchase Inventory'), (2, 'Purchase return'), (3, 'Purchase Allowance'), (4, 'Freight in'), (5, 'Pay Invoice'), (6, 'Sales')], null=True),
        ),
    ]
