# Generated by Django 3.1 on 2021-07-13 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_salesreturn_sale'),
        ('sole_proprietorship', '0005_auto_20210711_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.salesreturn'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Purchase Inventory'), (2, 'Purchase return'), (3, 'Purchase Allowance'), (4, 'Freight in'), (5, 'Pay Invoice'), (6, 'Sales'), (7, 'Sales Return')], null=True),
        ),
    ]
