# Generated by Django 3.0.7 on 2021-01-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0005_auto_20210101_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='comment',
            field=models.CharField(blank=True, help_text='Type a comment about your transaction', max_length=1500, null=True),
        ),
    ]
