# Generated by Django 3.0.7 on 2021-01-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0006_auto_20210101_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='comment',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
