# Generated by Django 3.1 on 2021-07-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_paymentsalesterm_sales_discount'),
        ('sole_proprietorship', '0007_auto_20210714_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='received_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.salespayment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Purchase Inventory'), (2, 'Purchase return'), (3, 'Purchase Allowance'), (4, 'Freight in'), (5, 'Pay Invoice'), (6, 'Sales'), (7, 'Sales Return'), (8, 'Sales Allowance'), (9, 'Received Payment')], null=True),
        ),
    ]
