# Generated by Django 3.0.7 on 2021-01-03 11:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sole_proprietorship', '0008_auto_20210103_1312'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accounts',
            name='unique_account',
        ),
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together={('owner', 'account')},
        ),
    ]
