# Generated by Django 3.1 on 2021-08-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0009_reportingperiodconfig_company_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['account'], name='account_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='date_idx'),
        ),
    ]
