# Generated by Django 3.1 on 2021-08-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0010_auto_20210815_0154'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accounts',
            name='account_idx',
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['account', 'owner'], name='account_idx'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['owner'], name='acc_owner_idx'),
        ),
    ]
