# Generated by Django 3.1.5 on 2021-01-31 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_delete_journalforinventoryreturn'),
        ('sole_proprietorship', '0010_auto_20210103_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='inventory_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryprice'),
        ),
        migrations.AddField(
            model_name='journal',
            name='inventory_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryreturn'),
        ),
        migrations.AddField(
            model_name='journal',
            name='purchase_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinventory'),
        ),
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.IntegerField(choices=[(1, 'Purchase Inventory'), (2, 'Purchase return'), (3, 'Purchase Allowance')], null=True),
        ),
    ]
