# Generated by Django 3.1 on 2021-08-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0012_auto_20210827_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='classification',
            field=models.CharField(blank=True, choices=[('Revenue', (('Sales', 'Sales'), ('Other Revenue and gains', 'Other Revenue and gains'))), ('Expenses', (('COGS', 'Cost of Goods Sold'), ('Operating Expense', 'Operating Expense'), ('Revenue-Contra', 'Revenue-Contra'), ('Other Expenses And Losses', 'Other Expenses And Losses')))], max_length=90, null=True),
        ),
    ]
