# Generated by Django 3.1 on 2021-03-14 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20210226_1930'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sole_proprietorship', '0012_auto_20210223_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=2500, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Purchase Inventory'), (2, 'Purchase return'), (3, 'Purchase Allowance'), (4, 'Freight in')], null=True)),
                ('inventory_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryprice')),
                ('inventory_return', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryreturn')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase_inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinventory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('num', 'owner'), name='unique_transaction'),
        ),
    ]
