# Generated by Django 3.1 on 2021-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0013_auto_20210829_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='classification',
            field=models.CharField(blank=True, choices=[('Current Assets', (('Current Assets', 'Current Assets'), ('Cash', 'Cash'), ('Marketable securities or short-term investments', 'Marketable securities or short-term investments'), ('Receivable', 'Receivable'), ('Inventory', 'Inventory'), ('prepaids', 'prepaids'))), ('Property, plant, and equipment', 'Property, plant, and equipment'), ('Intangible assets', 'Intangible assets'), ('Long-term investments', 'Long-term investments'), ('Contra Assets', 'Contra Assets'), ('Liabilities', (('Current liabilities', 'Current liabilities'), ('Long-term liabilities', 'liabilities'))), ('Revenue', (('Sales', 'Sales'), ('Other Revenue and gains', 'Other Revenue and gains'))), ('Expenses', (('COGS', 'Cost of Goods Sold'), ('Operating Expense', 'Operating Expense'), ('Revenue-Contra', 'Revenue-Contra'), ('Other Expenses And Losses', 'Other Expenses And Losses')))], max_length=90, null=True),
        ),
    ]
