# Generated by Django 3.1 on 2021-03-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20210226_1930'),
        ('sole_proprietorship', '0013_auto_20210314_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='inventory_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryprice'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='inventory_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryreturn'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchase_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseinventory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Purchase Inventory'), (2, 'Purchase return'), (3, 'Purchase Allowance'), (4, 'Freight in')], null=True),
        ),
    ]
