# Generated by Django 3.1 on 2021-03-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sole_proprietorship', '0014_auto_20210314_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sole_proprietorship.transaction'),
        ),
    ]
