# Generated by Django 3.1.3 on 2020-11-27 16:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200814_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
